apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: user-db
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-db
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  labels:
    app: userdb
spec:
    selector:
        matchLabels:
            app: userdb
    replicas: 1
    template:
        metadata:
            labels:
                app: userdb
        spec:
            containers:
            -   name: userdb
                image: techtest_techtest:latest
                imagePullPolicy: Always
                ports:
                    - containerPort: 5000
                readinessProbe:
                  tcpSocket:
                    port: 5000
                  initialDelaySeconds: 5
                  periodSeconds: 10
                livenessProbe:
                  tcpSocket:
                    port: 5000
                  initialDelaySeconds: 15
                  periodSeconds: 20
                resources:
                    requests:
                        memory: "64Mi"
                        cpu: "50m"
                    limits:
                        memory: "256Mi"
                        cpu: "500m"
