apiVersion: v1
kind: Service
metadata:
    name: userdb-service
    labels:
        app: userdb
spec:
    type: LoadBalancer
    selector:
        app: userdb
    ports:
     -  protocol: TCP
        name: http
        port: 8000
        targetPort: 5000
